Prioritize exposes tab order? #210
nurikk/z2m-frontend pull request #213
Opened 2020-12-29 18:04 UTC by timoline

2020-12-29 18:27 UTC, timoline commented
o damn , one space....think its easier to fix for you then for me

2020-12-29 23:36 UTC, nurikk requested changes

2020-12-29 23:36 UTC, nurikk commented on src/components/device-page/index.tsx
>              <ul className="nav nav-tabs">
you only need change here, don't touch any other places.
Kindly follow this order:

About, Exposes, Bind, Reporting, State, Clusters

2020-12-29 23:36 UTC, nurikk commented on src/components/device-page/index.tsx
> +type TabName = "exposes" | "reporting" | "bind" | "info" | "state" | "clusters" ;
No need change here

2020-12-29 23:36 UTC, nurikk commented on src/components/device-page/index.tsx
> +            case "exposes":
No need change here

2020-12-30 06:13 UTC, closed without merging

2020-12-30 06:13 UTC, timoline commented
Ok